version: "3.9"

services: 
    php:
        container_name: php-fpm
        build:
            context: ./docker/php
        volumes: 
            - "./:/var/www"            
        ports:
            - "9000:9000"
        restart: always
        
    nginx:
        image: nginx
        container_name: web
        restart: always
        volumes: 
            - "./:/var/www"   
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
#        command: [nginx-debug, '-g', 'daemon off;']
        depends_on: 
            - php
        ports: 
            - "8080:80"
        links: 
            - php